// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYDTAln0dGUOKtPaMM8D4H2Q8LNtKUOec',
    appId: '1:348825488560:android:9b75403151a65393e2ff75',
    messagingSenderId: '348825488560',
    projectId: 'leoconnect-6a3c0',
    storageBucket: 'leoconnect-6a3c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0wbuAGD9hEEGhoU_cGMpjREvc58xcEs',
    appId: '1:348825488560:ios:1aebbe3b9edcb48fe2ff75',
    messagingSenderId: '348825488560',
    projectId: 'leoconnect-6a3c0',
    storageBucket: 'leoconnect-6a3c0.firebasestorage.app',
    androidClientId: '348825488560-jhsc1bvcnmve0ngtb98m18ugqbjdmmtj.apps.googleusercontent.com',
    iosClientId: '348825488560-1lf0klq8auklv5f2vebb6a44t6t60r8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.leoconnect',
  );

}